# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
    - "5.5"
notifications:
    email: false
before_script:
    - npm install -g jshint
script:
    - jshint one-column-template/js/menuToggle.js
    - jshint calendar/js/main.js
